name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        cd fastapi-user-auth
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-auth-app:7 .
      
      

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/user-auth-app:7

    - name: Deploy to EC2 via SSH 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script:  |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/user-auth-app:7
          sudo docker stop user-auth-app || true
          sudo docker rm user-auth-app || true
          sudo docker run -d --name user-auth-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/user-auth-app:7
