name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      working-directory: ${{ github.workspace }}
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/user-auth-app:3 .
      

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME}}/user-auth-app:3

    - name: Deploy to EC2 via SSH 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script:  |
          docker pull ${{ secrets.DOCKER_USERNAME}}/user-auth-app:3
          docker stop user-auth-app || true
          docker rm user-auth-app || true
          docker run -d --name user-auth-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/user-auth-app:3
